In [2]:
import pandas as pd
import numpy as numpy

In [3]:
train = pd.read_csv("../data/processed/train.csv")
test = pd.read_csv("../data/processed/test.csv")

In [4]:
print("Train Shape:", train.shape)
print("Test Shape:",test.shape)

Train Shape: (77108, 42)
Test Shape: (17014, 41)

In [6]:
features = [
    "purchase_month",
    "purchase_day",
    "is_weekend",
    "estimated_delivery_days",
    "freight_to_price_ratio",
    "same_state",
    "seller_delay_rate",
    "seller_lat",
    "seller_lng",
    "customer_lat",
    "customer_lng",
    "distance_km",
    "is_late"
]

for feature in features:
    if feature in train.columns:
        print(f"{feature}:Present")
    else:
        print(f"{feature}:Missing")

purchase_month:Present
purchase_day:Present
is_weekend:Present
estimated_delivery_days:Present
freight_to_price_ratio:Present
same_state:Present
seller_delay_rate:Present
seller_lat:Present
seller_lng:Present
customer_lat:Present
customer_lng:Present
distance_km:Present
is_late:Present

In [5]:
print("Missing values in Train Dataset:")
print(train.isnull().sum())

print("\nMissing values in Test Dataset:")
print(test.isnull().sum())

Missing values in Train Dataset:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  12
order_delivered_carrier_date        1
order_delivered_customer_date       0
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_category_name            1086
product_name_lenght              1086
product_description_lenght       1086
product_photos_qty               1086
product_weight_g                   12
product_length_cm                  12
product_height_cm                  12
product_width_cm                   12
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
is_late                             0
purchase_month                      0
purchase_day                        0
is_weekend                          0
estimated_delivery_days             0
freight_to_price_ratio              0
same_state                          0
seller_delay_rate                   0
seller_lat                          0
seller_lng                          0
customer_lat                        0
customer_lng                        0
distance_km                         0
dtype: int64

Missing values in Test Dataset:
order_id                           0
customer_id                        0
order_status                       0
order_purchase_timestamp           0
order_approved_at                 24
order_delivered_carrier_date     300
order_delivered_customer_date    476
order_estimated_delivery_date      0
order_item_id                    115
product_id                       115
seller_id                        115
shipping_limit_date              115
price                            115
freight_value                    115
customer_unique_id                 0
customer_zip_code_prefix           0
customer_city                      0
customer_state                     0
product_category_name            364
product_name_lenght              364
product_description_lenght       364
product_photos_qty               364
product_weight_g                 116
product_length_cm                116
product_height_cm                116
product_width_cm                 116
seller_zip_code_prefix           115
seller_city                      115
seller_state                     115
purchase_month                     0
purchase_day                       0
is_weekend                         0
estimated_delivery_days            0
freight_to_price_ratio           115
same_state                         0
seller_delay_rate                  0
seller_lat                         0
seller_lng                         0
customer_lat                       0
customer_lng                       0
distance_km                        0
dtype: int64

In [9]:
train_missing = train.isnull().sum()
train_missing = train_missing[train_missing >0].sort_values(ascending=False)

test_missing = test.isnull().sum()
test_missing = test_missing[test_missing>0].sort_values(ascending=False)


print("Missing values in Train:")
print(train_missing)

print("\nmissing values in test:")
print(test_missing)

Missing values in Train:
product_name_lenght             1086
product_category_name           1086
product_description_lenght      1086
product_photos_qty              1086
product_weight_g                  12
order_approved_at                 12
product_height_cm                 12
product_length_cm                 12
product_width_cm                  12
order_delivered_carrier_date       1
dtype: int64

missing values in test:
order_delivered_customer_date    476
product_category_name            364
product_name_lenght              364
product_description_lenght       364
product_photos_qty               364
order_delivered_carrier_date     300
product_width_cm                 116
product_length_cm                116
product_height_cm                116
product_weight_g                 116
seller_id                        115
order_item_id                    115
product_id                       115
seller_zip_code_prefix           115
shipping_limit_date              115
price                            115
freight_value                    115
seller_state                     115
seller_city                      115
freight_to_price_ratio           115
order_approved_at                 24
dtype: int64

In [10]:
train.dtypes.to_frame(name="Data Type")

                              Data Type
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
order_item_id                   float64
product_id                       object
seller_id                        object
shipping_limit_date              object
price                           float64
freight_value                   float64
customer_unique_id               object
customer_zip_code_prefix          int64
customer_city                    object
customer_state                   object
product_category_name            object
product_name_lenght             float64
product_description_lenght      float64
product_photos_qty              float64
product_weight_g                float64
product_length_cm               float64
product_height_cm               float64
product_width_cm                float64
seller_zip_code_prefix          float64
seller_city                      object
seller_state                     object
is_late                         float64
purchase_month                    int64
purchase_day                     object
is_weekend                        int64
estimated_delivery_days           int64
freight_to_price_ratio          float64
same_state                        int64
seller_delay_rate               float64
seller_lat                      float64
seller_lng                      float64
customer_lat                    float64
customer_lng                    float64
distance_km                     float64

In [11]:
train.describe()

,order_item_id,price,freight_value,customer_zip_code_prefix,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,...,is_weekend,estimated_delivery_days,freight_to_price_ratio,same_state,seller_delay_rate,seller_lat,seller_lng,customer_lat,customer_lng,distance_km
count,77108.000000,77108.000000,77108.000000,77108.000000,76022.000000,76022.000000,76022.000000,77096.000000,77096.000000,77096.000000,...,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000
mean,1.199992,119.417761,19.899504,35153.418400,48.782392,787.321525,2.211715,2091.863352,30.134080,16.567020,...,0.224763,23.420929,0.320523,0.362245,0.079758,-22.800519,-47.239325,-21.252267,-46.220972,593.596923
std,0.714400,179.910469,15.558290,29893.354773,10.027444,650.465084,1.726492,3735.887593,16.100522,13.397751,...,0.417429,8.837262,0.337725,0.480652,0.068870,2.691641,2.334720,5.536256,4.019672,586.371530
min,1.000000,0.850000,0.000000,1003.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,-32.079231,-63.893565,-33.689948,-72.668881,0.000000
25%,1.000000,39.900000,13.050000,11325.000000,42.000000,348.000000,1.000000,300.000000,18.000000,8.000000,...,0.000000,18.000000,0.134832,0.000000,0.043478,-23.607473,-48.829744,-23.589483,-48.118347,185.708734
50%,1.000000,74.900000,16.250000,24344.000000,52.000000,603.000000,1.000000,700.000000,25.000000,13.000000,...,0.000000,23.000000,0.231701,0.000000,0.070588,-23.425556,-46.744092,-22.928999,-46.634985,431.682589
75%,1.000000,134.177500,21.150000,59068.000000,57.000000,985.000000,3.000000,1800.000000,38.000000,20.000000,...,0.000000,28.000000,0.394874,1.000000,0.101562,-21.757321,-46.522287,-20.188080,-43.700266,785.340686
max,21.000000,6729.000000,409.680000,99980.000000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,...,1.000000,155.000000,26.235294,1.000000,1.000000,-2.501242,-34.855616,42.184003,-8.723762,8677.911622

In [13]:
train[
    [   "price",
     "freight_value",
     "estimated_delivery_days",
     "freight_to_price_ratio",
     "seller_delay_rate",
     "distance_km"   
    ]
].describe()

,price,freight_value,estimated_delivery_days,freight_to_price_ratio,seller_delay_rate,distance_km
count,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000,77108.000000
mean,119.417761,19.899504,23.420929,0.320523,0.079758,593.596923
std,179.910469,15.558290,8.837262,0.337725,0.068870,586.371530
min,0.850000,0.000000,2.000000,0.000000,0.000000,0.000000
25%,39.900000,13.050000,18.000000,0.134832,0.043478,185.708734
50%,74.900000,16.250000,23.000000,0.231701,0.070588,431.682589
75%,134.177500,21.150000,28.000000,0.394874,0.101562,785.340686
max,6729.000000,409.680000,155.000000,26.235294,1.000000,8677.911622

In [14]:
correlation = train.corr(numeric_only=True)
print(correlation["is_late"].sort_values(ascending=False))

is_late                       1.000000
seller_delay_rate             0.254209
customer_lng                  0.071682
distance_km                   0.068754
customer_lat                  0.056161
freight_value                 0.041839
customer_zip_code_prefix      0.026507
product_weight_g              0.023732
seller_lat                    0.022233
freight_to_price_ratio        0.018068
price                         0.017789
product_length_cm             0.017146
product_height_cm             0.012788
product_width_cm              0.006208
product_name_lenght           0.004976
product_photos_qty            0.000786
product_description_lenght   -0.001589
seller_lng                   -0.002109
is_weekend                   -0.008175
order_item_id                -0.014135
purchase_month               -0.022727
seller_zip_code_prefix       -0.032194
same_state                   -0.054758
estimated_delivery_days      -0.062639
Name: is_late, dtype: float64